### ISSUE TITLE
Kernels are reported as successfully installed when they aren't

### ISSUE THREAD

**Issue by es20490446e** [manjaro/manjaro-settings-manager#125] opened 2017-11-28 21:44 UTC
HOW TO REPRODUCE:
1. Disconnect from the Internet.
2. Open the application "Kernel".
3. On any non installed kernel, click on the "install" button. Follow the screens.

RESULT:
Eventually you reach to a screen that says that all changes were made successfully, but if you click on the link "show details" you actually can see that the installation failed.

**Comment by Huluti** [comment] 2017-12-09 18:03
@Kirek @philmmanjaro I'm not very comfortable with C ++ but I've the impression that there are some inconsistencies in the **ActionDialog.cpp** file : 
Lines 146-149 : 
```c++
if ( job->error() == 0 )
    jobDone( true, tr ( "Changes failed, click on 'Show Details' for more information" ) );
else
    jobDone( false, tr ( "Changes failed, click on 'Show Details' for more information" ) );
```
Why does two states (true, false) have the same message ?

Lines 179-194 : 
```c++
if (success) {
  m_jobSuccesful = true;
  if (message != NULL)
    m_messageLabel-> setText(tr("Changes were made successfully"));
  else
    m_messageLabel->setText(message);
} else {
  m_jobSuccesful = false;
  if (message != NULL)
    m_messageLabel->setText(tr("Changes failed, click on 'Show Details' for more information"));
  else
    m_messageLabel->setText(message);
}
```

Why verify if message is not NULL and then not use it ?

I don't know if the problem is related with these code blocks but ...

**Comment by es20490446e** [comment] 2017-12-09 23:02
Bugs I see:
1. "if (message != NULL)" should be "if (message == NULL)".
2. The variable "success" is true in cases where the command is failing.

Root cause: needs unit testing.

**Comment by vfjpl** [comment] 2017-12-10 11:06
For me job->error() is returning 0 no matter what…

**Comment by es20490446e** [comment] 2017-12-10 13:20
Where's "error()" declared?

**Comment by vfjpl** [comment] 2017-12-10 13:31
https://api.kde.org/frameworks/kcoreaddons/html/classKJob.html#ae0ac2567b61681f4811d128825fbcd0b
?

**Comment by es20490446e** [comment] 2017-12-10 14:26
In C++ conditionals aren't integers, but they have their own type.

So the line:
`if ( job->error() == 0 )`

Should be:
`if (job->error())`

**Comment by vfjpl** [comment] 2017-12-10 15:12
No, I don't think so.( I have also tested this right now). if(job->error()) is the same as if(job->error() == true) or if(job->error() == 1). 0 is the same as false and 1 is the same as true. Also if you are returning error code it can be different than simply true or false so you have to have ability to differentiate. Also the documentation states that this function return int. int KJob::error()const (link above)

**Comment by es20490446e** [comment] 2017-12-10 17:16
If in the Terminal I enter:
sudo pacman --sync --noconfirm cheese; echo $?

The return code is 1, with the same error messages than in the Kernel application.

It is 0 however only if the package is already available in the system to install, but not already installed.

**Comment by es20490446e** [comment] 2017-12-10 17:37
So the problematic line is:
[auto](http://en.cppreference.com/w/cpp/language/auto) job = [qobject_cast](http://doc.qt.io/qt-5/qobject.html#qobject_cast)<[KAuth::ExecuteJob*](https://api.kde.org/frameworks/kauth/html/classKAuth_1_1ExecuteJob.html)>( [kjob](https://api.kde.org/frameworks/kcoreaddons/html/classKJob.html#ae0ac2567b61681f4811d128825fbcd0b) );

**Comment by vfjpl** [comment] 2017-12-10 18:26
Test my code. I just simply did
`    connect( kAuthJob, &KAuth::ExecuteJob::result,
             [this] ( KJob *kjob )
    {
        if ( kjob->error() == 0 )
            jobDone( true, tr ( "Changes were made successfully" ) );
        else
            jobDone( false, tr ( "Changes failed, click on 'Show Details' for more information" ) );
} );`

**Comment by es20490446e** [comment] 2017-12-10 19:04
I can't test it right now, but as I read the qobject cast isn't even necessary?

```
connect (kAuthJob, &KAuth::ExecuteJob::result, [this] (KJob *kjob) {
    if (kjob->error())  jobDone (false, tr ("Failed"));
    else                jobDone (true, tr ("Success"));
});
```

**Comment by vfjpl** [comment] 2017-12-12 18:00
Please test v0.5.4-8 Please do extensive testing and write everything you observe.

**Comment by es20490446e** [comment] 2017-12-12 18:24
Added to my todo list.

**Comment by es20490446e** [comment] 2017-12-23 23:41
I can't do it myself right now because my Internet connection during holiday is minimal. Only after Christmas.

**Comment by vfjpl** [comment] 2018-01-28 16:45
@es20490446e Any news?

**Comment by es20490446e** [comment] 2018-01-29 10:51
Reading the above merge pull request, the fix would be available in next upgrade.

**Comment by vfjpl** [comment] 2018-02-23 21:52
@es20490446e Fix for this was available in v0.5.4-8 by this https://github.com/manjaro/packages-extra/commit/182b68d3e1592b4871483e818a10a3ea0cd43a07#diff-282c1dba5e2fbf7c997798b6fde80a3e. Merge was done when no bug report showed up. :)

**Closed** 2018-02-24 02:04 UTC

**Comment by vfjpl** [comment] 2018-02-24 08:26
@es20490446e what about your testing? Is it fixed for you? :)

**Comment by es20490446e** [comment] 2018-02-24 13:37
Yes.
